InventorySolution/InventorySolution/Controllers/InventareController.cs
using InventorySolution.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Inventory.Core.Domain;
using Inventory.Services;
using Inventory.Core.Domain.Inventare;

namespace InventorySolution.Controllers
{
    public class InventareController : Controller
    {
        //
        // GET: /Inventare/

        public ActionResult Index()
        {
            InventareModel model = new InventareModel()
            {
                Inventare = SVC.Inventare.GetInventare(true).Select(inventar =>
                    new InventarDataModel
                    {
                        InventarId = inventar.Id,
                        Denumire = inventar.Denumire,
                        Tip = inventar.TipEntity ?? new Tip(),
                        Gestiune = inventar.GestiuneEntity ?? new Gestiune(),
                        Laborator = inventar.LaboratorEntity ?? new Laborator(),
                        Sursa = inventar.SursaEntity ?? new Sursa(),
                        Natura = inventar.Natura.ParseEnum<Natura>(),
                        AnPFun = inventar.AnPFun,
                        PVerbal = inventar.PVerbal,
                        NrInventar = inventar.NrInventar,
                        Serie = inventar.Serie,
                        Pret = inventar.Pret,
                        Valoare = inventar.Valoare,
                        Cantitate = inventar.Cantitate,
                        Mentiuni = inventar.Mentiuni,
                        
                    }).ToList(),
                Message = TempData["InventareMessage"] as MessageModel
            };

            return View(model);
        }

        //
        // GET: /Inventare/Details/5

        public ActionResult Details(int id)
        {
            var inventar = SVC.Inventare.GetInventar(id);
            if (inventar == null)
            {
                TempData["InventareMessage"] = new MessageModel
                {
                    Message = new HtmlString(string.Format("Inventarul #{0} nu exista", id)),
                    Type = MessageType.Error,
                    Icon = MessageIcon.ErrorIcon
                };

                return RedirectToAction("Index");
            }

            Tip tip = SVC.Tipuri.GetTip(inventar.TipId.Value) ?? new Tip();
            
            InventarDataModel inventarDetails = new InventarDataModel()
            {
                InventarId = inventar.Id,
                Denumire = inventar.Denumire,
                Tip = inventar.TipEntity ?? new Tip(),
                Gestiune = inventar.GestiuneEntity ?? new Gestiune(),
                Laborator = inventar.LaboratorEntity ?? new Laborator(),
                Sursa = inventar.SursaEntity ?? new Sursa(),
                Natura = inventar.Natura.ParseEnum<Natura>(),
                AnPFun = inventar.AnPFun,
                PVerbal = inventar.PVerbal,
                NrInventar = inventar.NrInventar,
                Serie = inventar.Serie,
                Pret = inventar.Pret,
                Valoare = inventar.Valoare,
                Cantitate = inventar.Cantitate,
                Mentiuni = inventar.Mentiuni,
                Message = TempData["InventareMessage"] as MessageModel
            };
            Calculator calculator = null;
            CalculatorModel calculatorDetails = null;
            var sursaCalc = SVC.Surse.GetSursaByNameInvariant(Sursa.SURSA_CALCULATOARE);
            if (sursaCalc != null && inventar.SursaId == sursaCalc.Id)
            {
                calculator = SVC.Calculatoare.GetCalculator(id);
                if (calculator == null)
                {
                    TempData["calculatorMessage"] = new MessageModel
                    {
                        Message = new HtmlString(string.Format("Calculatorul #{0} nu exista", id)),
                        Type = MessageType.Error,
                        Icon = MessageIcon.ErrorIcon
                    };
                    return RedirectToAction("Index");
                }
                else
                {

                    calculatorDetails = new CalculatorModel
                    {
                        CalculatorId = calculator.Id,
                        Procesor = calculator.Procesor,
                        Frecventa = calculator.Frecventa,
                        Hdd = calculator.Hdd,
                        Ram = calculator.Ram,
                        CdRom = calculator.CdRom,
                        Floppy = calculator.Floppy,
                        Zipp = calculator.Zipp,
                        Monitor = calculator.Monitor,
                        Tastatura = calculator.Tastatura,
                        Accesorii = calculator.Accesorii,
                        Mentiuni = calculator.Mentiuni,
                        Mouse = calculator.Mouse,
                        PlacaBaza = calculator.PlacaBaza,
                        PlacaVideo = calculator.PlacaVideo,
                        CdW = calculator.CdW,
                        CdWR = calculator.CdWR,
                        Dvd = calculator.Dvd,
                        PlacaRetea = calculator.PlacaRetea,
                        TvTuner = calculator.TvTuner,
                        Modem = calculator.Modem,
                        Message = TempData["calculatorMessage"] as MessageModel
                    };
                }
            }

            InventarModel model = new InventarModel
            {
                Inventar = inventarDetails,
                Calculator = calculatorDetails ?? new CalculatorModel(),
                Message = TempData["InventareMessage"] as MessageModel
            };
            return View("Inventar", model);
        }

        //
        // GET: /Inventare/Create
        [HttpGet]
        public ActionResult Create(int? gestiuneId)
        {
            var gestiuni = SVC.Gestiuni.GetGestiuni();
            var laboratoare = SVC.Laboratoare.GetLaboratoare();
            var surse = SVC.Surse.GetSurse();
            var tipuri = SVC.Tipuri.GetTipuri();

            var model = new NewInventarModel
            {
                Message = TempData["InventarMessage"] as MessageModel,
                Inventar = new NewInventarDataModel()
                {
                    SelectedGestiuneId = -1,
                    Gestiuni = gestiuni,
                    SelectedLaboratorId = -1,
                    Laboratoare = laboratoare,
                    SelectedSursaId = -1,
                    Surse = surse,
                    SelectedTipId = -1,
                    Tipuri = tipuri
                },
                Calculator = new CalculatorModel(),
            };

            if (gestiuni == null || gestiuni.Count <= 0
                || laboratoare == null || laboratoare.Count <= 0
                || surse == null || surse.Count <= 0
                || tipuri == null || tipuri.Count <= 0)
            {
                StringBuilder msg = new StringBuilder();
                if (gestiuni == null || gestiuni.Count <= 0)
                {
                    msg.AppendFormat("Nu exista gestiuni.");
                }
                if (laboratoare == null || laboratoare.Count <= 0)
                {
                    msg.AppendFormat("Nu exista laboratoare.");
                }

                if (surse == null || surse.Count <= 0)
                {
                    msg.AppendFormat("Nu exista surse.");
                }

                if (tipuri == null || tipuri.Count <= 0)
                {
                    msg.AppendFormat("Nu exista tipuri.");
                }

                model.Message = new MessageModel
                {
                    Message = new HtmlString(msg.ToString()),
                    Type = MessageType.Warning,
                    Icon = MessageIcon.ErrorIcon
                };
            }
            else
            {
                model.Message = TempData["InventareMessage"] as MessageModel;
            }

            if (gestiuneId.HasValue)
            {
                var gestiune = SVC.Gestiuni.GetGestiune(gestiuneId.Value);
            }

            return View(model);
        }

        //
        // POST: /Inventare/Create

        [HttpPost]
        public ActionResult Create(NewInventarModel model, string save, string saveAndNew)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MessageModel message = null;
                    Gestiune gestiune = SVC.Gestiuni.GetGestiune(model.Inventar.SelectedGestiuneId);

                    Inventar inventar = new Inventar
                    {
                        Denumire = model.Inventar.Denumire,
                        AnPFun = model.Inventar.AnPFun,
                        GestiuneId = model.Inventar.SelectedGestiuneId,
                        LaboratorId = model.Inventar.SelectedLaboratorId,
                        PVerbal = model.Inventar.PVerbal,
                        Pret = model.Inventar.Pret,
                        Cantitate = model.Inventar.Cantitate ?? 1,
                        NrInventar = model.Inventar.NrInventar,
                        Serie = model.Inventar.Serie,
                        TipId = model.Inventar.SelectedTipId,
                        Natura = model.Inventar.Natura.ToString(),
                        SursaId = model.Inventar.SelectedSursaId,
                        Mentiuni = model.Inventar.Mentiuni
                    };

                    //verifica daca este sursa CALCULATOARE, daca da adauga calculator
                    ServiceResult serviceResult;
                    var sursaCalc = SVC.Surse.GetSursaByNameInvariant(Sursa.SURSA_CALCULATOARE);
                    if (sursaCalc != null && inventar.SursaId == sursaCalc.Id)
                    {
                        Calculator calculator = new Calculator
                        {

InventorySolution/InventorySolution/Views/Inventare/DisplayTemplates/CalculatorDisplay.cshtml
@model InventorySolution.Models.CalculatorModel


<div class="row" id="calculator-edit">
    <!-- calculatoare -->
    <div class="col-lg-12">
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Procesor)
            </div>
            <div class="col-md-4">
                @Model.Procesor
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Frecventa)
            </div>
            <div class="col-md-4">
                @Model.Frecventa
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Hdd)
            </div>
            <div class="col-md-4">
                @Model.Hdd
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Ram)
            </div>
            <div class="col-md-4">
                @Model.Ram
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.CdRom)
            </div>
            <div class="col-md-4">
                @Model.CdRom
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Floppy)
            </div>
            <div class="col-md-4">
                @Model.Floppy
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Zipp)
            </div>
            <div class="col-md-4">
                @Model.Zipp
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Monitor)
            </div>
            <div class="col-md-4">
                @Model.Monitor
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Tastatura)
            </div>
            <div class="col-md-4">
                @Model.Tastatura
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Mouse)
            </div>
            <div class="col-md-4">
                @Model.Mouse
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.PlacaBaza)
            </div>
            <div class="col-md-4">
                @Model.PlacaBaza
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.PlacaVideo)
            </div>
            <div class="col-md-4">
                @Model.PlacaVideo
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.CdW)
            </div>
            <div class="col-md-4">
                @Model.CdW
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Dvd)
            </div>
            <div class="col-md-4">
                @Model.Dvd
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.PlacaRetea)
            </div>
            <div class="col-md-4">
                @Model.PlacaRetea
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.TvTuner)
            </div>
            <div class="col-md-4">
                @Model.TvTuner
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Modem)
            </div>
            <div class="col-md-4">
                @Model.Modem
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Accesorii)
            </div>
            <div class="col-md-4">
                @Model.Accesorii
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Mentiuni)
            </div>
            <div class="col-md-10">
                @Model.Mentiuni
            </div>
        </div>
    </div>
</div>

InventorySolution/InventorySolution/Views/Inventare/DisplayTemplates/InventarDisplay.cshtml
@model InventorySolution.Models.InventarDataModel


<div class="row" id="inventar-edit">
    <!-- inventar -->
    <div class="col-lg-12">
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.InventarId)
            </div>
            <div class="col-md-4">
                <a href="@Url.Action("Edit", "Inventare", new {id = Model.InventarId})"> @string.Format("#{0}", Model.InventarId)</a>
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Denumire)
            </div>
            <div class="col-md-4">
                @Model.Denumire
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Gestiune)
            </div>
            <div class="col-md-4">
                @Model.Gestiune.Nume
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Laborator)
            </div>
            <div class="col-md-4">
                @Model.Laborator.Nume
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.AnPFun)
            </div>
            <div class="col-md-4">
                @Model.AnPFun
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.PVerbal)
            </div>
            <div class="col-md-4">
                @Model.PVerbal
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Pret)
            </div>
            <div class="col-md-4">
                @Model.Pret
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Cantitate)
            </div>
            <div class="col-md-4">
                @Model.Cantitate
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Valoare)
            </div>
            <div class="col-md-4">
                @Model.Valoare
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.NrInventar)
            </div>
            <div class="col-md-4">
                @Model.NrInventar
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Serie)
            </div>
            <div class="col-md-4">
                @Model.Serie
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Tip)
            </div>
            <div class="col-md-4">
                @Model.Tip.Nume
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Natura)
            </div>
            <div class="col-md-4">
                @Model.Natura
            </div>
            <div class="col-md-2">
                @Html.LabelFor(m => m.Sursa)
            </div>
            <div class="col-md-4">
                @Model.Sursa.Nume
            </div>
        </div>
        <div class="row">
            <div class="col-md-2">
                @Html.LabelFor(m => m.Mentiuni)
            </div>
            <div class="col-md-10">
                @Model.Mentiuni
            </div>
        </div>
    </div>
</div>