InventorySolution/InventorySolution/Controllers/GestiuniController.cs
using InventorySolution.Models;
using Inventory.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Inventory.Core.Domain;

namespace InventorySolution.Controllers
{
    public class GestiuniController : Controller
    {
        private IGestiuni GestiuniService
        {
            get
            {
                return SVC.Gestiuni;
            }
        }

        //
        // GET: /Gestiune/

        public ActionResult Index()
        {
            GestiuneViewModel model = new GestiuneViewModel()
            {
                Gestiune = GestiuniService.GetGestiuni()
                .Select(g => new GestiuneModel
                {
                    GestiuneId = g.Id,
                    Nume = g.Nume,
                    Prenume = g.Prenume,
                    Catedra = g.Catedra
                }).ToList()
            };

            return View(model);
        }
        //
        // GET: /Gestiune/Create

        public ActionResult Create(int? id)
        {
            Gestiune gestiune = null;
            if (id.HasValue)
                gestiune = GestiuniService.GetGestiune(id.Value);

            gestiune = gestiune ?? new Gestiune();
            return PartialView("EditorTemplates/GestiuneEditor", new GestiuneModel()
                {
                    GestiuneId = gestiune.Id,
                    Nume = gestiune.Nume,
                    Prenume = gestiune.Prenume,
                    Catedra = gestiune.Catedra
                });
        }

        //
        // POST: /Gestiune/Create

        [HttpPost]
        public ActionResult AddOrUpdateGestiune(int? id)
        {
            ServiceResult service = new ServiceResult();
            var msg = String.Empty;
            try
            {
                // TODO: Add insert logic here
                int gestiuneId;
                int.TryParse(Request.Form["pk"], out gestiuneId);
                var nume = Request.Form["value[nume]"];
                var prenume = Request.Form["value[prenume]"];
                var catedra = Request.Form["value[catedra]"];

                var gestiune = new Gestiune
                {
                    Id = gestiuneId,
                    Nume = nume,
                    Prenume = prenume,
                    Catedra = catedra
                };

                if (gestiuneId > 0)
                {//update
                    service = GestiuniService.UpdateGestiune(gestiune);
                    msg = string.Format("gestiune #{0} actualizata cu succes", gestiuneId);
                }
                else
                {//adaugare
                    service = GestiuniService.AddGestiune(gestiune);
                    msg = string.Format("gestiune #{0} adaugata cu succes", gestiuneId);
                }
                //return RedirectToAction("Index");
            }
            catch
            {
                msg = string.Format("am intampinat o problema");
                //return View();
            }
            if (service.OperationResult < OperationResult.Success)
            {
                msg = string.Format("Am intampitan o eroarea");
            }
            return Json(new { Id = service.EntityId, Message = msg }, JsonRequestBehavior.DenyGet);
        }

        //
        // GET: /Gestiune/Delete/5
 
        public ActionResult Delete(int id)
        {
            GestiuniService.DeleteGestiune(id);
            return RedirectToAction("Index");
        }
    }
}

InventorySolution/InventorySolution/Views/Gestiuni/EditorTemplates/GestiuneEditor.cshtml
@model InventorySolution.Models.GestiuneModel

@{
    ViewBag.Title = "GestiuneEditor";
}

<div class="gestiune row list-group-item">
    <div class="col-md-5">
        <div class="col-sm-2 gestiune-id">
            @string.Format("#{0}", Model.GestiuneId)
        </div>
        <div class="col-sm-10">
            <a href="#" class="gestiune-body" id="@string.Format("gestiune_{0}", Model.GestiuneId)" data-type="address" data-pk="@Model.GestiuneId" data-value="@Model.ToValue()"></a><br />
        </div>
    </div>
    <div class="col-md-2">
        <a href="#" style="float: left" class="edit-gestiune-button btn-sm btn-default input-sm">
            <i class="glyphicon glyphicon-pencil"></i>
        </a>
        <a data-href="@Url.Action("Delete", "Gestiuni", new {id = Model.GestiuneId})" style="float: left" class="btn btn-sm btn-danger input-sm" data-toggle="modal" data-target="#confirm-delete">
            <i class="glyphicon glyphicon-trash"></i>
        </a>
    </div>
</div>